feat(backend): add Prisma component on Backend Project

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,6 +1,6 @@
 echo 'Formarting code on Backend'
-# npm run format || (echo 'Lint on Backend Failed' && exit 1)
-echo 'Checking Lint for backend'
-# npm run lint:backend || (echo 'Lint on Backend Failed' && exit 1)
+npm run format || (echo 'Lint on Backend Failed' && exit 1)
+echo 'Checking Lint for Backend'
+npm run lint:backend || (echo 'Lint on Backend Failed' && exit 1)
 
 echo 'Lint Finished'
